export const welcomeElements: any[] = [
  {
    type: "text",
    version: 1,
    versionNonce: 0,
    isDeleted: false,
    id: "welcome-title",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    angle: 0,
    x: 500,
    y: 200,
    strokeColor: "#1e1e1e",
    backgroundColor: "transparent",
    width: 800,
    height: 50,
    seed: 1,
    groupIds: ["welcome-message-group"],
    frameId: null,
    roundness: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
    fontSize: 36,
    fontFamily: 1,
    text: "Welcome to an Excalidraw Whiteboard! 🎨",
    textAlign: "left",
    verticalAlign: "top",
    containerId: null,
    originalText: "Welcome to an Excalidraw Whiteboard! 🎨",
    lineHeight: 1.25 as const,
    baseline: 25
  },
  {
    type: "text",
    version: 1,
    versionNonce: 0,
    isDeleted: false,
    id: "support-text",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    angle: 0,
    x: 500,
    y: 300,
    strokeColor: "#1e1e1e",
    backgroundColor: "transparent",
    width: 800,
    height: 300,
    seed: 1,
    groupIds: ["welcome-message-group"],
    frameId: null,
    roundness: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
    fontSize: 24,
    fontFamily: 1,
    text: "This is an open source project powered by Excalidraw.\n\nSupport the project by:\n\n• Visiting excalidraw.com\n• Try Excalidraw+ at plus.excalidraw.com\n• Star us on GitHub at github.com/excalidraw/excalidraw",
    textAlign: "left",
    verticalAlign: "top",
    containerId: null,
    originalText: "This is an open source project powered by Excalidraw.\n\nSupport the project by:\n\n• Visiting excalidraw.com\n• Try Excalidraw+ at plus.excalidraw.com\n• Star us on GitHub at github.com/excalidraw/excalidraw",
    lineHeight: 1.25 as const,
    baseline: 25
  }
];
